// Maps each process ID to the relative path of its HTML process map file.
// The #canvas-wrap div inside each file is displayed in the gap analysis tool.

const PROCESS_MAP_FILES = {

    // ── SCM ──────────────────────────────────────────────────────────────────
    'scm-1.1':   'Working maps/SCM/scm-1.1.html',
    'scm-1.2.1': 'Working maps/SCM/scm-1.2.1.html',
    'scm-1.2.2': 'Working maps/SCM/scm-1.2.2.html',
    'scm-1.3':   'Working maps/SCM/scm-1.3.html',
    'scm-1.4':   'Working maps/SCM/scm-1.4.html',
    'scm-1.5.1': 'Working maps/SCM/scm-1.5.1.html',
    'scm-1.5.2': 'Working maps/SCM/scm-1.5.2.html',
    'scm-1.6':   'Working maps/SCM/scm-1.6.html',
    'scm-1.7':   'Working maps/SCM/scm-1.7.html',
    'scm-1.8':   'Working maps/SCM/scm-1.8.html',
    'scm-1.9':   'Working maps/SCM/scm-1.9.html',
    'scm-1.10':  'Working maps/SCM/scm-1.10.html',

    // ── Finance ──────────────────────────────────────────────────────────────
    'fin-1.1':  'Working maps/Finance/fin-1.1.html',
    'fin-1.2':  'Working maps/Finance/fin-1.2.html',
    'fin-1.3':  'Working maps/Finance/fin-1.3.html',
    'fin-1.4':  'Working maps/Finance/fin-1.4.html',
    'fin-1.5':  'Working maps/Finance/fin-1.5.html',
    'fin-1.6':  'Working maps/Finance/fin-1.6.html',
    'fin-1.7':  'Working maps/Finance/fin-1.7.html',
    'fin-2.1':  'Working maps/Finance/fin-2.1.html',
    'fin-2.2':  'Working maps/Finance/fin-2.2.html',
    'fin-3.1':  'Working maps/Finance/fin-3.1.html',
    'fin-4.1':  'Working maps/Finance/fin-4.1.html',
    'fin-4.2':  'Working maps/Finance/fin-4.2.html',
    'fin-4.3':  'Working maps/Finance/fin-4.3.html',

    // ── HR ───────────────────────────────────────────────────────────────────
    'hr-1.1':   'Working maps/HR/hr-1.1.html',
    'hr-1.2':   'Working maps/HR/hr-1.2.html',
    'hr-1.3':   'Working maps/HR/hr-1.3.html',
    'hr-1.4':   'Working maps/HR/hr-1.4.html',
    'hr-1.5':   'Working maps/HR/hr-1.5.html',
    'hr-1.6':   'Working maps/HR/hr-1.6.html',
    'hr-1.7':   'Working maps/HR/hr-1.7.html',
    'hr-1.8':   'Working maps/HR/hr-1.8.html',
    'hr-1.9':   'Working maps/HR/hr-1.9.html',
    'hr-1.10':  'Working maps/HR/hr-1.10.html',
    'hr-1.11':  'Working maps/HR/hr-1.11.html',
    'hr-1.12':  'Working maps/HR/hr-1.12.html',
    'hr-1.13':  'Working maps/HR/hr-1.13.html',
    'hr-1.14':  'Working maps/HR/hr-1.14.html',
    'hr-1.15':  'Working maps/HR/hr-1.15.html',
    'hr-1.16':  'Working maps/HR/hr-1.16.html',
    'hr-1.17':  'Working maps/HR/hr-1.17.html',
    'hr-1.18':  'Working maps/HR/hr-1.18.html',
    'hr-1.19':  'Working maps/HR/hr-1.19.html',
    'hr-1.20':  'Working maps/HR/hr-1.20.html',
    'hr-1.21':  'Working maps/HR/hr-1.21.html',
    'hr-1.22':  'Working maps/HR/hr-1.22.html',

    // ── Investment ───────────────────────────────────────────────────────────
    'inv-1.1.1': 'Working maps/Investment/inv-1.1.1.html',
    'inv-1.1.2': 'Working maps/Investment/inv-1.1.2.html',
    'inv-1.1.3': 'Working maps/Investment/inv-1.1.3.html',
    'inv-1.1.4': 'Working maps/Investment/inv-1.1.4.html',
    'inv-1.1.5': 'Working maps/Investment/inv-1.1.5.html',
    'inv-1.1.6': 'Working maps/Investment/inv-1.1.6.html',
    'inv-1.2.1': 'Working maps/Investment/inv-1.2.1.html',
    'inv-1.3.1': 'Working maps/Investment/inv-1.3.1.html',
    'inv-1.3.2': 'Working maps/Investment/inv-1.3.2.html',
    'inv-1.3.3': 'Working maps/Investment/inv-1.3.3.html',
    'inv-2.1.1': 'Working maps/Investment/inv-2.1.1.html',
    'inv-2.1.2': 'Working maps/Investment/inv-2.1.2.html',
    'inv-2.2.1': 'Working maps/Investment/inv-2.2.1.html',
    'inv-2.3.1': 'Working maps/Investment/inv-2.3.1.html',

    // ── IT ───────────────────────────────────────────────────────────────────
    'it-1.1':    'Working maps/IT/it-1.1.html',
    'it-1.2':    'Working maps/IT/it-1.2.html',
    'it-1.3':    'Working maps/IT/it-1.3.html',
    'it-1.4':    'Working maps/IT/it-1.4.html',
    'it-1.5':    'Working maps/IT/it-1.5.html',
    'it-1.6':    'Working maps/IT/it-1.6.html',
    'it-1.7':    'Working maps/IT/it-1.7.html',
    'it-1.8':    'Working maps/IT/it-1.8.html',
    'it-1.9':    'Working maps/IT/it-1.9.html',
    'it-1.10':   'Working maps/IT/it-1.10.html',
    'it-1.11':   'Working maps/IT/it-1.11.html',
    'it-1.12':   'Working maps/IT/it-1.12.html',
    'it-1.13.1': 'Working maps/IT/it-1.13.1.html',
    'it-1.13.2': 'Working maps/IT/it-1.13.2.html',
    'it-1.14':   'Working maps/IT/it-1.14.html',
    'it-1.15':   'Working maps/IT/it-1.15.html',
    'it-1.16':   'Working maps/IT/it-1.16.html',
    'it-1.17':   'Working maps/IT/it-1.17.html',

    // ── Risk ─────────────────────────────────────────────────────────────────
    'risk-1.1':   'Working maps/Risk/risk-1.1.html',
    'risk-1.2.1': 'Working maps/Risk/risk-1.2.1.html',
    'risk-1.2.2': 'Working maps/Risk/risk-1.2.2.html',
    'risk-1.3':   'Working maps/Risk/risk-1.3.html',
    'risk-1.4':   'Working maps/Risk/risk-1.4.html',
    'risk-2.1':   'Working maps/Risk/risk-2.1.html',
    'risk-2.2':   'Working maps/Risk/risk-2.2.html',
    'risk-2.3':   'Working maps/Risk/risk-2.3.html',
    'risk-2.4':   'Working maps/Risk/risk-2.4.html',
    'risk-2.5':   'Working maps/Risk/risk-2.5.html',
    'risk-2.6':   'Working maps/Risk/risk-2.6.html',
    'risk-3.1':   'Working maps/Risk/risk-3.1.html',
    'risk-3.2':   'Working maps/Risk/risk-3.2.html',
    'risk-4.1':   'Working maps/Risk/risk-4.1.html',
    'risk-5.1':   'Working maps/Risk/risk-5.1.html',
    'risk-5.2':   'Working maps/Risk/risk-5.2.html',
    'risk-5.3.1': 'Working maps/Risk/risk-5.3.1.html',
    'risk-5.3.2': 'Working maps/Risk/risk-5.3.2.html',
    'risk-6.1':   'Working maps/Risk/risk-6.1.html',

    // ── Marketing ────────────────────────────────────────────────────────────
    'mkt-1.1':  'Working maps/Marketing/mkt-1.1.html',
    'mkt-1.2':  'Working maps/Marketing/mkt-1.2.html',
    'mkt-1.3':  'Working maps/Marketing/mkt-1.3.html',
    'mkt-1.4':  'Working maps/Marketing/mkt-1.4.html',
    'mkt-1.5':  'Working maps/Marketing/mkt-1.5.html',
    'mkt-1.6':  'Working maps/Marketing/mkt-1.6.html',
    'mkt-1.7':  'Working maps/Marketing/mkt-1.7.html',

    // ── Cosec ────────────────────────────────────────────────────────────────
    'cosec-1.1':   'Working maps/Cosec/cosec-1.1.html',
    'cosec-1.2.1': 'Working maps/Cosec/cosec-1.2.1.html',
    'cosec-1.2.2': 'Working maps/Cosec/cosec-1.2.2.html',
    'cosec-1.3':   'Working maps/Cosec/cosec-1.3.html',
    'cosec-1.4':   'Working maps/Cosec/cosec-1.4.html',
    'cosec-1.5':   'Working maps/Cosec/cosec-1.5.html',
    'cosec-2.1':   'Working maps/Cosec/cosec-2.1.html',

    // ── PMO ──────────────────────────────────────────────────────────────────
    'pmo-1.1':  'Working maps/PMO/pmo-1.1.html',
    'pmo-1.2':  'Working maps/PMO/pmo-1.2.html',
    'pmo-1.3':  'Working maps/PMO/pmo-1.3.html',
    'pmo-1.4':  'Working maps/PMO/pmo-1.4.html',
    'pmo-1.5':  'Working maps/PMO/pmo-1.5.html',
    'pmo-1.6':  'Working maps/PMO/pmo-1.6.html',
    'pmo-1.7':  'Working maps/PMO/pmo-1.7.html',
};