const PROCESS_STEPS = {
    'scm-1.1': [
        'Finance - Planning Cycle Initiated',
        'Finance - Provide Budgets to Inform Procurement and Demand Plan',
        'Line Departments - Provide input on items to be added to Procurement/Demand Plan',
        'SCM Manager - Develop Procurement/Demand Plan',
        'SCM Manager - Submit to EXCO for Approval',
        'EXCO - EXCO Approves Procurement Plan?',
        'SCM Manager - Attend to Changes Required by EXCO',
        'SCM Manager - Submit to CEO for Final Approval',
        'CEO - Submit to CEO for Final Approval',
        'SCM Admin - Load Approved Plan on eTenders',
        'SCM Admin - Submit Procurement Plan to Treasury',
        'SCM Admin - Quarterly Reporting to Treasury',
        'EXCO - Revision of Procurement / Demand Plan Required?',
        'EXCO - Procurement Plan Submitted to Treasury',
    ],

    'scm-1.2.1': [
        'Line Department - Procurement Need Identified',
        'Line Department - Submit Needs Analysis to Finance',
        'Finance - Does Finance Approve budget in the Needs Analysis?',
        'SCM Admin - Prepare 3-Quotes/RFQ from CSD',
        'SCM Unit - Parallel Activities',
        'SCM Unit - Check If Adequate Information (Specs) Is Available Online For Quote',
        'SCM Unit - Check Specs, Market Cost, Budget',
        'SCM Unit - Misalignments Identified Post Background Check?',
        'SCM Unit - Inform Line Department of Misalignments',
        'SCM Unit - Submit 3-Quotes/RFQ Document to Line Department for Approval',
        'Line Department - Does Line Department Approve 3-Quotes/RFQ Documents?',
        'SCM Unit - Send out/Advertise Quote to Service Providers',
        'SCM Admin - 3-Quotes or RFQ?',
        'SCM Admin - 3 Working Days',
        'SCM Admin - 10 Working Days to closure',
        'SCM Admin - Evaluate RFQ',
        'Line Department - Liaise with Service Provider',
        'SCM Admin - Issue LOA or PO to Successful Service Provider after RFP and 3-Quotes Closes',
        'SCM Admin - Quotation Process Closes',
    ],

    'scm-1.2.2': [
        'Line Department - Procurement Need Identified',
        'Line Department - Submit Spec or Request SCM to Source Similar Specs',
        'Line Department - Prepare and Submit Needs Analysis',
        'Finance - Does Finance Approve budget in the Needs Analysis?',
        'SCM Admin - Set Up Bid Spec Committee',
        'Bid Spec Committee - Interrogate Specification and Prompt Line Department to Update Spec',
        'Bid Spec Committee - Send to CEO for Approval',
        'CEO - CEO Approves?',
        'Line Department - Incorporate Changes and Resubmit to Bid Spec Committee',
        'SCM Admin - Load Approved Specification on eTenders',
        'SCM Admin - Close RFP',
        'SCM Admin - 21 Working Days for RFP Close',
        'Bid Spec Committee - Perform Bid Evaluation and Bid Adjudication Before Contracting',
        'Bid Spec Committee - RFP Cycle Closes',
    ],

    'scm-1.3': [
        'SCM Manager - Supplier Appointment Confirmed',
        'SCM Manager - Share Procurement Documents with Legal',
        'Legal - Generate SLA',
        'SCM Admin - Share SLA with Successful Company for Input',
        'SCM Admin - Major Changes Required?',
        'Legal - Schedule Meeting with Representation from Successful Company to Address Major Changes',
        'Legal - Incorporate Changes into SLA',
        'Legal - Load SLA and Memo onto Doxit',
        'CEO - Sign Off on Memo and Sign Off on SLA',
        'CEO - Major Changes Required?',
        'SCM Admin - Send Signed SLA to Service Provider for Signature',
        'SCM Admin - Capture SLA Information onto the Contracts Register',
        'Line Department - Assume Contract Ownership and Management',
        'Line Department - Contracting Executed',
    ],

    'scm-1.4': [
        'Service Provider - Service or Goods Delivered',
        'SCM - Check Delivery Against PO and Quotation',
        'SCM - Are all items included in the Delivery?',
        'SCM - Return to Service Provider',
        'Service Provider - Deliver Missing Items',
        'SCM - IT Equipment or Standard Goods/Services?',
        'IT - Checks Spec',
        'Line Department - Approve Invoice',
        'SCM - Approve Delivery Note',
        'Line Department - Sign Off Delivery Note',
        'SCM - Send Invoice to Finance',
        'Finance - Delivery Note Signed Off',
    ],

    'scm-1.5.1': [
        'SCM - Contract Management Cycle Initiated',
        'SCM - Monitor Contracts Register — Update Spend Against Actual and Planned; Monitor Contract Dates',
        'SCM - Inform Line Departments of Contracts Coming to an End',
        'SCM - Check Excel Report on Dates and Validity; Share with Line Department',
        'SCM - Update Register and Distribute Monthly',
        'SCM - Contract Above Budget?',
        'SCM - Check Invoice for Additional Costs Not on Contract',
        'Legal - Inquire on Deviation Memo or Quote',
        'SCM - Monthly Contract Register Updated',
    ],

    'scm-1.5.2': [
        'Line Department - Variance or Deviation Identified',
        'Line Department - Advises SCM to Check if Within Threshold',
        'SCM - Is This a Variance or a Deviation?',
        'Line Department - Draft Variance Memo',
        'SCM - Time-Based or Financial Variance?',
        'SCM - Legal Does Addendum on Dates; Follow Normal Signing Process',
        'CEO/CFO - CEO Approves Amount and Dates; Legal Does Addendum on Value and Dates',
        'SCM - Issue PO Stating Date and Value Changes',
        'SCM - Determine Type of Deviation and Draft Deviation Memo',
        'SCM - CEO Approves Deviation Memo?',
        'SCM - Issue Additional PO or Letter of Award to Service Provider',
        'SCM - Update Contracts Register and Report',
        'SCM - Variance or Deviation Approved',
        'SCM - Deviation',
        'SCM - Variance',
        'SCM - Time Based Only',
        'CEO/CFO - Financial Variance',
    ],

    'scm-1.6': [
        'SCM - Quarterly Supplier Evaluation Cycle Initiated',
        'SCM - Send Supplier Evaluation Form to Line Departments',
        'Line Departments - Complete and Return Evaluation Form',
        'Line Departments - Positive or Negative Feedback?',
        'Line Departments - Complete and Return Evaluation Form',
        'SCM - Sit with Line Department to Understand Negative Feedback',
        'SCM - Long Term Supplier?',
        'SCM - Meeting Between SCM, Service Provider and Line Department',
        'SCM - Resolution is implemented',
        'SCM - Issue Resolved?',
        'Legal - Terminate or Enforce Penalty Clauses',
        'SCM - File Assessment Form',
        'SCM - Supplier Evaluation Filed',
    ],

    'scm-1.7': [
        'SCM - SCM Compliance Cycle Initiated',
        'SCM - Confirm RFP and Tender Compliance Requirements',
        'SCM - Communicate Standard Compliance Requirements to Bidders',
        'SCM - Check Compliance Documents on Closing Date',
        'SCM - Bidder Meets All Compliance Requirements?',
        'SCM - Disqualify Non-Compliant Bidder and Issue Regret Letter',
        'SCM - Check BEE Certificate and Tax Compliance Monthly',
        'SCM - Develop Compliance Checklist File',
        'SCM - Compliance File Complete',
    ],

    'scm-1.8': [
        'SCM - SCM Policy Review - 2 Year Legislation Updates',
        'SCM - Review SCM Policy and Preferential Procurement Policy',
        'SCM - Draft Updated Policy',
        'SCM - Submit Policy Update to EXCO, Social Partners and Audit and Risk Committee',
        'EXCO / Social Partners - EXCO and Committee Support Obtained?',
        'EXCO / Social Partners - Submit to Board for Approval',
        'Board - Board Approves Policy?',
        'SCM - Send Approved Policy to All Staff via Email Communication',
        'SCM - SCM Policy Updated and Communicated',
    ],

    'scm-1.9': [
        'SCM - Asset Procurement Initiated',
        'SCM - Receive and Sign Delivery Of Asset',
        'SCM - Check the Asset Against the Quote and RFQ Specifications',
        'Finance - Allocate Asset to Department and Tags for Insurance',
        'Finance - Tag Asset and Capture on Asset Register',
        'Finance - Is Asset being disposed?',
        'SCM - Facilitate Disposal Committee and Disposal Memo for Approval',
        'Disposal Committee - Disposal Committee Decides Disposal Method',
        'CEO - CEO Approves Disposal Memo?',
        'Finance - Remove Asset from Asset Register',
        'Finance - Asset Management Cycle Complete',
    ],

    'scm-1.10': [
        'SCM - Monthly Reporting Cycle Initiated',
        'SCM - Compile Monthly Report',
        'SCM - Compile Quarterly Report Against Procurement Plan',
        'SCM - Report on Deviations and Irregular, Fruitless and Wasteful and Unauthorized Expenditure Within Timeframe',
        'SCM - Deviation or Irregular Expenditure?',
        'SCM - Deviation Above 15%?',
        'SCM - Process Minor Deviation Within Allowed Threshold',
        'SCM - Process Formal Deviation; Single Source Remaining Work if Post-Contract',
        'SCM - What happens In the case of these expenditures?',
        'SCM - SCM Reporting Cycle Complete',
    ],

    // ── IT ──────────────────────────────────────────────────────────────────────
    'it-1.1': [
        'Business User - Issue/Incident Occurs',
        'Business User - Report Issue',
        'IT Support/ Technical Team - Log Request & Assign Priority',
        'IT Support/ Technical Team - Attend to the Issue and Update the Request',
        'IT Support/ Technical Team - What is the Outcome After Review?',
        'IT Support/ Technical Team - Change Status to Duplicate',
        'IT Support/ Technical Team - Close Duplicate Request',
        'IT Support/ Technical Team - Change Status to Resolved',
        'IT Support/ Technical Team - Close Request as Resolved',
        'IT Manager - Review Escalated Issue',
        'IT Manager - Can Issue be Resolved by IT Manager?',
        'IT Manager - Resolve Issue',
        'Service Provider - Resolve Issue',
    ],

    'it-1.2': [
        'HR - New Employee Appointment Confirmed',
        'HR - Submit Onboarding Request',
        'HR - Complete IT Access Request Form',
        'Line Manager - Confirm User Details and Role',
        'IT - Review Request',
        'IT - Request Approved?',
        'IT - Create AD and System Accounts',
        'IT - Allocate Role-Based Access',
        'IT - Grant Physical Access to Premises',
        'IT - Prepare and Assign Device',
        'IT - Conduct Induction and Security Briefing',
        'IT - Follow-up with User to Sign AUP',
        'IT - Onboarding Complete',
    ],

    'it-1.3': [
        'HR / Line Manager - Identify Training Needs',
        'User - Identify Training Needs',
        'IT - Schedule Training Session',
        'IT - Session Confirmed With No Conflicts?',
        'IT - Conduct Training',
        'User - Provide Feedback',
        'IT - Feedback Received?',
        'IT - Training Complete — Report Delivered to Management',
    ],

    'it-1.4': [
        'HR - Employee Role Change Confirmed',
        'HR - Receive Mover Request',
        'Line Manager - Review Access Rights for New Role',
        'Line Manager - Updated Access Profile Approved?',
        'IT Desktop Technician - Remove Old Access',
        'IT Desktop Technician - Grant New Access',
        'IT Desktop Technician - New Access Provisioned Within SLA?',
        'IT Manager - Grant New Access',
        'IT Manager - Compliance Check Passed?',
        'IT Manager - Role Change Complete',
    ],

    'it-1.5': [
        'HR - Employee Termination Confirmed',
        'HR - Receive Exit Notification and Submit HR Termination Form',
        'IT Desktop Technician - Collect IT Assets from Employee',
        'IT Desktop Technician - Complete IT Termination Form',
        'IT Desktop Technician - IT Termination Form Signed?',
        'IT Desktop Technician - Disable System Access',
        'IT Desktop Technician - Archive Email and Data',
        'IT Desktop Technician - File IT Termination Form to SharePoint',
        'IT Desktop Technician - Backup User Data and Reset Device',
        'Finance - Confirm Asset Recovery',
        'IT Manager - Verify Termination Compliance',
        'IT Manager - All Termination Steps Compliant?',
        'IT Manager - Termination Complete',
    ],

    'it-1.6': [
        'User - Change Requirement Identified',
        'User - Fill Out Change Request Form',
        'Desktop Technician/Service Provider - Change Request Logged',
        'Desktop Technician/Service Provider - Change Request Form Complete?',
        'Desktop Technician/Service Provider - Change Request Logged onto System',
        'IT Manager - Assess Risk and Impact',
        'IT Manager - Is There a Cost Implication?',
        'IT Manager - Implement Change',
        'IT Manager - Submit Needs Analysis to Finance',
        'SCM - Follow SCM Process to Appoint Service Provider',
        'IT Manager - Submit Change Report to IT Steering Committee',
        'IT Steering Committee - Monthly Review',
        'IT Steering Committee - Change Approved/Declined',
        'IT Steering Committee - Action IT Steering Committee Feedback',
        'IT Steering Committee - Change Report Created',
        'IT Steering Committee - Change Report Tabled to Board Committee',
    ],

    'it-1.7': [
        'Desktop Technician - Bi-Annual Review Cycle Starts',
        'Desktop Technician - Generate Access Listing',
        'Line Managers - Validate Access List',
        'Line Managers - Is the Access List Accurate?',
        'Line Managers - Notify IT and Fill Out User Access Form',
        'Desktop Technician - Update Access List',
        'IT Manager - Review and Sign Off',
        'Desktop Technician - Update Monthly Report for SteerCo',
        'Desktop Technician - Access Updated',
    ],

    'it-1.8': [
        'Desktop Technician/Service Provider - Scheduled Scan Triggered',
        'Desktop Technician/Service Provider - Initiate Vulnerability Scan Across All Systems',
        'Desktop Technician/Service Provider - Weekly Cycle',
        'IT Manager - Review and Approve',
        'IT Manager - Approve Patch?',
        'Desktop Technician/Service Provider - Apply Patch After Approval',
        'Desktop Technician/Service Provider - Log Vulnerabilities to Report',
        'Desktop Technician/Service Provider - Add to Monthly Report for SteerCo',
        'Desktop Technician/Service Provider - Weekly Cycle Ends',
    ],

    'it-1.9': [
        'Desktop Technician - Monthly/Quarterly Reporting Cycle Starts',
        'Desktop Technician - Pull Extracts From All Activities and Consolidate',
        'Desktop Technician - Draft Report',
        'IT Manager - Review & Validate Report',
        'IT Manager - Is the Report Adequate?',
        'IT Manager - Submit to EXCO for Approval',
        'EXCO - Review and Recommend Report for Filing',
        'IT Manager - Consolidate 3 Months Extracts into Quarterly Report',
        'IT Steering Committee - Receive, Review and Recommend Possible Changes',
        'IT Steering Committee - Have Changes Been Applied?',
        'Desktop Technician - Apply Changes',
        'IT Steering Committee - Table to Board',
        'IT Steering Committee - Reporting Cycle Ends',
    ],

    'it-1.10': [
        'IT Manager - SLA Breach/Dispute Identified',
        'IT Manager - Engage Vendor to Discuss Breach',
        'IT Manager - Conduct Review Meeting with Vendor',
        'IT Manager - Propose and Agree on Resolution',
        'IT Manager - Resolution Achieved?',
        'SCM - Set-up Mediation Meeting with Vendor',
        'SCM - Agreement Achieved?',
        'IT Manager - Vendor Management End',
        'IT Manager - Hand Over to Legal',
        'Legal - Set-up Legal Meeting with Vendor',
        'Legal - Agreement Achieved?',
        'Legal - Agreement Reached',
        'Legal - Apply Sanctions/Penalties',
    ],

    'it-1.11': [
        'Desktop Technician/Service Provider - Scheduled Scan Triggered',
        'Desktop Technician/Service Provider - Initiate Cybersecurity Scan Across All Systems',
        'Desktop Technician/Service Provider - Weekly Cycle',
        'IT Manager - Review and Approve',
        'IT Manager - Patch Approved?',
        'Desktop Technician/Service Provider - Apply Patch After Approval',
        'Desktop Technician/Service Provider - Log Vulnerabilities to Report',
        'Desktop Technician/Service Provider - Develop Monthly Report for SteerCo',
        'Desktop Technician/Service Provider - Weekly Cycle Ends',
    ],

    'it-1.12': [
        'Desktop Technician/Service Provider - Security Incident Detected',
        'Desktop Technician/Service Provider - Initiate Security Scan Across All Systems',
        'Desktop Technician/Service Provider - Weekly Cycle',
        'IT Manager - Review and Approve',
        'IT Manager - Patch Approved?',
        'Desktop Technician/Service Provider - Apply Patch After Approval',
        'Desktop Technician/Service Provider - Log Vulnerabilities to Report',
        'Desktop Technician/Service Provider - Develop Monthly Report for SteerCo',
        'Desktop Technician/Service Provider - Weekly Cycle Ends',
    ],

    'it-1.13.1': [
        'IT Manager - 2-Year Cycle / As Needed',
        'IT Manager - Identify Critical Systems',
        'IT Manager - Draft BC/DR Plan',
        'IT Manager - Review BC/DR Plan',
        'EXCO - Approve Plan?',
        'Board - Approve Plan?',
        'IT Manager - Simulate Incident and Follow Plan',
        'IT Manager - Create Test Report',
        'IT Manager - Does Plan Meet Goals?',
        'IT Manager - Activate DR',
        'IT Manager - BC/DR Plan Cycle Closed',
    ],

    'it-1.13.2': [
        'Desktop Technician/Service Provider - Incident Occurs',
        'Desktop Technician/Service Provider - Initiate Incident Scan Across All Systems',
        'Desktop Technician/Service Provider - Weekly Cycle',
        'IT Manager - Review and Approve',
        'IT Manager - Approve Patch?',
        'Desktop Technician/Service Provider - Apply Patch After Approval',
        'Desktop Technician/Service Provider - Log Vulnerabilities to Report',
        'Desktop Technician/Service Provider - Add to Monthly Report for SteerCo',
        'Desktop Technician/Service Provider - Weekly Cycle Ends',
    ],

    'it-1.14': [
        'IT Manager - 2-Year Cycle / As Needed',
        'IT Manager - Identify Policies for Review',
        'IT Manager - Draft Updated Policy',
        'IT Manager - Review IT Policy',
        'EXCO - Approve Policy?',
        'Board - Approve Policy?',
        'IT Manager - Test Policy Effectiveness',
        'IT Manager - Create Review Report',
        'IT Manager - Does Policy Meet Goals?',
        'IT Manager - Apply Policy Changes and Updates',
        'IT Manager - IT Policy Cycle Closed',
    ],

    'it-1.15': [
        'IT Manager - Resource Need Identified',
        'IT Manager - Assess Resource Needs',
        'IT Manager - Is the Resource Permanent or Temporary?',
        'HR - Fill Vacancy Following HR Process',
        'SCM - Appoint External Service Provider Following SCM Process',
        'IT Manager - Conduct Skills Assessment',
        'IT Manager - Resource Management Cycle Ends',
    ],

    'it-1.16': [
        'SCM - Asset Procurement Need Identified',
        'SCM - Procure Asset Following SCM Process',
        'Finance - Tag and Allocate Asset',
        'Finance - Conduct Annual Audit',
        'IT - Is Asset Being Disposed?',
        'Disposal Committee - Decide on Disposal Method',
        'IT - Decommission Asset',
        'IT - Asset Management Cycle Complete',
    ],

    'it-1.17': [
        'Department - Acquisition Need Identified',
        'Department - Fill Acquisition Form',
        'IT Manager - Draft RFP/RFQ',
        'SCM - Review RFP/RFQ',
        'SCM - Is RFP/RFQ Compliant?',
        'SCM - Source Vendors',
        'BEC/QEC - Perform Technical Evaluation',
        'SCM - Award and Procure',
        'SCM - Feeds into Asset Management',
    ],
    // ── HR ──────────────────────────────────────────────────────────────────────
    'hr-1.1': [
        'Line Manager - Recruitment Requisition Approved',
        'Line Manager - Review Requisition and Decide on Recruitment Strategy',
        'Line Manager - Role Exists?',
        'Line Manager - Create New Role',
        'Line Manager - Advertise Role',
        'HR Officer - Collect Applications and Screen Candidates Against Criteria',
        'Line Manager - Shortlisting Meeting with Line Manager',
        'HR Officer - Send applications',
        'Line Manager - Conduct Interviews',
        'HR Officer - Background Checks and Psycometrics',
        'CEO - Offer or Rejection?',
        'Applicant - Rejection',
        'HR Officer - Alert of Decision - Decline',
        'HR Officer - Alert of Decision – Send offer letter',
        'Applicant - Offer',
        'Applicant - Send Rejection Letter',
        'Applicant - Accept or Reject Offer?',
        'Applicant - Reject',
        'Applicant - Proceed to onboarding',
        'Applicant - Accept',
    ],

    'hr-1.2': [
        'HR Manager - Performance Management Cycle Initiated',
        'HR Manager - Plan and Set Measurable Goals',
        'HR Manager - Develop Performance Management Framework',
        'Line Manager - Sign Off Performance Agreement for the Financial Year',
        'Line Manager - Set Annual KPA/I\'s for the Year',
        'Line Manager - 2 Weeks after Quarter ends',
        'HR Manager - Communicate Timeframe for Quarterly KPA/I Submissions',
        'Line Manager - Build Portfolio of Evidence and Perform Self Assessment',
        'Line Manager - Conduct Performance Reviews',
        'HR Manager - Submit Annual Performance Reviews for Moderation',
        'HR and Ethics Committee - Executive or Non-Executive Role?',
        'EXCO - Moderation at Financial Year End',
        'HR and Ethics Committee - Moderation at Financial Year End',
        'HR and Ethics Committee - Flag Anomalies and Identify Reasons',
        'HR and Ethics Committee - Alert Employees on Bonus Status and Issue Bonus Letters',
        'HR and Ethics Committee - Performance Management Cycle Complete',
    ],

    'hr-1.3': [
        'Managers - Training and Skills Development Cycle Initiated',
        'Managers - Identify Skills and Training Gaps',
        'HR - Conduct Training Needs Analysis',
        'HR - Compile WSP for Board Approval and SETA Submission',
        'Board - WSP Approved by Board?',
        'HR - WSP Implementation and Sourcing of Training Quotations',
        'Training Service Provider - Schedule, Conduct and Coordinate Training Intervention',
        'HR - Evaluate Training',
        'HR - Submit Annual Training Plan to SETA',
        'HR - Training Cycle Complete',
    ],

    'hr-1.4': [
        'HR Officer - Prepare Payroll Memorandums, Letters and Benefit Spreadsheets; Collect Monthly Payroll Input',
        'HR Officer - Monthly Payroll Cycle Initiated – 10th Every Month',
        'HR Officer - Review all payroll input before capturing',
        'Finance - Confirms Validity of Employee Bank Accounts',
        'HR Officer - Parallel Activities',
        'Payroll Admin/Finance - Capture Payroll Data and Leave Records',
        'HR Manager - Review Payroll Reports and Variance Report',
        'HR Manager - Payroll Reports Approved?',
        'HR Manager - No',
        'HR Manager - Yes',
        'Payroll Admin/Finance - Release Salaries and Payslips',
        'Payroll Admin/Finance - Submit Payroll Recon to SARS and Declare to Labour Department',
        'Payroll Admin/Finance - Statutory Submissions Made — Payroll Cycle Complete',
        'Payroll Admin/Finance - 15th Of Each Month',
        'Payroll Admin/Finance - ≥ 3 days',
    ],

    'hr-1.5': [
        'HR - Remuneration Review Cycle Initiated',
        'SCM - Procure External Service Provider for Benchmarking',
        'HR - Submit Benchmark Salaries and Job Grading Data to Service Provider',
        'External Service Provider - Perform Grading and Benchmarking',
        'Board - Submit Updated Benchmark Data for Board Approval',
        'Board - Approves Benchmark Data?',
        'HR - Implement Approved Salary Benchmarking and Job Grading Report',
        'HR - Prepare Employee Letters and Update Job Profiles',
        'Payroll Admin - Process Reviewed Salaries and Adjust Employee Deductions',
        'Payroll Admin - Reviewed Salaries Processed — Employee Deductions Adjusted',
    ],

    'hr-1.6': [
        'HR Manager - Employee Benefits Event Triggered',
        'HR Officer - Liaise with Broker for Medical Aid and Pension Fund Application(New Employees) or Updates(Existing Employees)',
        'HR Officer - Send Medical Aid Certificates and Appointment of Pension Fund Beneficiaries to Broker',
        'Broker - Store Records on Broker System',
        'HR Manager - Confirm Data is Correct?',
        'HR Officer - Submit Final Employee Benefits Documents to Payroll for Deductions',
        'Payroll Admin - Process New and Updated Medical Aid and Pension Fund Deductions',
        'Payroll Admin - Deductions Correctly Processed?',
        'HR Officer - Employee Being Terminated?',
        'Payroll Admin - Employee Benefits Cycle Complete',
        'Payroll Admin - Process New and Updated Medical Aid and Pension Fund Deductions',
    ],

    'hr-1.7': [
        'HR - Submit Leave Request',
        'Line Manager - Receive and Review Leave Application',
        'Line Manager - Leave Approved?',
        'Employee - Resubmit Addressing Comments',
        'Line Manager - Leave Day(s) Booked',
        'HR - Leave Balance Updated by System – SAGE People 300',
        'Payroll Admin - Submit Leave History Report',
        'Payroll Admin - Monthly Leave Cycle Complete',
    ],

    'hr-1.8': [
        'Line Manager - Employee Wellness Need Identified',
        'HR Officer - Identify Employee Needs',
        'SCM - Appoint EAP Service Provider',
        'HR Officer - Communicate Programme to Staff',
        'Service Provider - Conduct Wellness Initiatives and Provide Counselling Support',
        'HR Officer - Wellness Initiatives Delivered — Quarterly Cycle Complete',
    ],

    'hr-1.9': [
        'HR Officer - New Employee Appointment Confirmed',
        'HR Officer - Issue Onboarding Forms',
        'HR Officer - Day 1 Introduction to Team and Facilities',
        'IT - Set Up SAGE (ESS) Access',
        'Department Heads - Conduct Induction Sessions',
        'Department Heads - Assign Mentor',
        'HR Officer - Onboarding and Induction Complete',
    ],

    'hr-1.10': [
        'Line Manager - Misconduct Identified',
        'HR - Report Misconduct to HR',
        'HR - Conduct Investigation',
        'HR - Decision to Proceed or Not?',
        'HR - No',
        'HR - Yes',
        'HR - Decide Informal or Formal Inquiry',
        'HR - Informal or Formal Inquiry?',
        'HR - Coordinate Formal Inquiry',
        'HR - Formal',
        'HR - File Disciplinary Outcome',
        'HR - Informal',
        'HR - Disciplinary Record Filed — Process Complete',
    ],

    'hr-1.11': [
        'Employee - Grievance Complaint Raised',
        'Employee - Is Employee CEO or Not?',
        'Employee - CEO',
        'HR and Ethics Committee - Submit Grievance to Board',
        'Employee - Submit Grievance to Line Manager — Stage 1 Informal',
        'Employee - Not CEO',
        'Line Manager - Was Grievance Resolved at Stage 1?',
        'HR and Ethics Committee - No',
        'Employee - Is Grievance against CEO',
        'Employee - Yes',
        'Line Manager - Stage 2 — Formal Grievance to Next Level Manager',
        'Line Manager - Was Grievance Resolved at Stage 2?',
        'Employee - Yes',
        'Employee - Grievance Resolved',
        'Employee - Resolve Grievance',
        'Employee - Yes',
        'Employee - No',
        'HR and Ethics Committee - Formal grievance hearing – Stage 3',
        'HR and Ethics Committee - Escalate to Stage 2',
        'HR and Ethics Committee - Escalated to the CCMA',
        'HR and Ethics Committee - Was it resolved?',
        'HR and Ethics Committee - Yes',
        'HR and Ethics Committee - Escalate to MEC',
        'HR and Ethics Committee - No',
    ],

    'hr-1.12': [
        'HR Officer - HR Records Event Triggered',
        'HR Officer - Receive, Verify and File Employee Documents',
        'HR Officer - Capture Employee Data on System',
        'Employees - Update New Employee Data and Store Securely',
        'HR Officer - Employee Being Terminated?',
        'Terminated Employees - Complete Termination Checklist and Obtain Line Manager Sign-Off',
        'Terminated Employees - Archive Employee File for 5 Years',
        'HR Officer - HR Records Updated',
        'HR Officer - No',
    ],

    'hr-1.13': [
        'Finance Team - Reporting Cycle Initiated',
        'Finance Team - Gather Financial Data and HR Records',
        'HR - Collect Performance Data, Gather HR Data and Reconcile',
        'HR - Check for Errors, Missing Information and Reconcile HR Data',
        'HR - Data Complete and Reconciled?',
        'HR - No',
        'HR - Yes',
        'HR - Identify Trends, Variances and Root Causes',
        'HR - Draft Reports with Key Metrics and Tailor for Monthly or Quarterly Reporting',
        'HR - Monthly or Quarterly Report?',
        'HR - Monthly',
        'EXCO - Submit Monthly Report EXCO',
        'HR and Ethics Committee - Quarterly Submit Quarterly Report to Board',
        'HR and Ethics Committee - Reports Submitted',
        'HR and Ethics Committee - Quarterly',
        'HR and Ethics Committee - Monthly',
    ],

    'hr-1.14': [
        'CSI Committee - CSI Funding Cycle Initiated',
        'CSI Committee - Identify Eligible Projects and Send Out Adverts',
        'CSI Committee - Evaluate Proposals Against CSI Policy',
        'CSI Committee - Proposals Meet CSI Policy Requirements?',
        'CSI Committee - No',
        'CSI Committee - Yes',
        'CSI Committee - Shortlist as a Committee per CSI Policy',
        'HR - Submit CSI Committee Recommendation to EXCO',
        'EXCO - Approve Recommendation?',
        'EXCO - No',
        'HR - Yes',
        'HR - Confirm Bank Details for Disbursement of Funds',
        'HR - Monitor and Verify Funds Served the Purpose',
        'HR - Report to EXCO and HR and Ethics Committee',
        'HR - CSI Process Complete',
    ],

    'hr-1.15': [
        'HR Officer - OHS Cycle Initiated',
        'HR Officer - Conduct Risk Assessment',
        'HR Officer - Appointment of OHS Representatives',
        'Training Officer - Coordinate Training for SHE Rep and Fire Marshal',
        'OHS Reps - Monitor Hazards and Record Incidents',
        'OHS Reps - Ongoing OHS Monitoring',
        'OHS Reps - Was there any Incident?',
        'OHS Reps - No',
        'OHS Reps - Yes',
        'OHS Reps - Coordinate Resolution',
        'OHS Reps - OHS Monitoring Complete',
    ],

    'hr-1.16': [
        'Line Managers - Succession Planning Cycle Initiated',
        'Line Managers - Determine Which Positions are Essential for Organisational Success',
        'HR Manager - Outline Skills, Knowledge and Behaviours for Each Critical Role',
        'HR Manager - Evaluate Employees Against Competencies and Identify High Potential Individuals',
        'HR Manager - Provide Training, Mentoring and Stretch Assignments',
        'HR Manager - Map Potential Successors to Critical Roles',
        'HR Manager - Track Progress of Successors Through Regular Reviews',
        'HR Manager - Succession Plans and Reviews Updated',
    ],

    'hr-1.17': [
        'Leadership - Policy Development Cycle Initiated',
        'HR - Identify Needs or Gaps in Policies',
        'HR - Review Labour Laws and Benchmark Against Peers',
        'HR - Develop Clear Draft Policy',
        'EXCO - Is the draft approved?',
        'HR - Review Policy Draft',
        'HREC - Present Draft to HREC',
        'HREC - HREC Supports Draft Policy?',
        'BoD - Obtain Sign Off from the Board of Directors',
        'BoD - Approves Policy?',
        'BoD - Policy Approved',
        'HR - No',
        'HR - Yes',
    ],

    'hr-1.18': [
        'Equity Committee - Employment Equity Cycle Initiated',
        'Equity Committee - Review Workforce Demographics, Identify Gaps and Assess Compliance',
        'HR - Draft Employment Equity Policy and Define Objectives, Scope and Responsibilities',
        'HR - Engage Stakeholders, Collect Feedback and Ensure Inclusivity',
        'HR - Develop Action Plans with Measurable Targets and Assign Responsibilities',
        'HR - Roll Out Initiatives — Workforce Accommodation and Recruitment Strategies',
        'HR - EE Initiatives Implemented — Workforce Diversity Improved and Policy Updated',
    ],

    'hr-1.19': [
        'HR Officer - Labour Law Changes, Union Agreements, Socio-Political Factors',
        'HR Officer - Analyse Labour Markets, Union Dynamics and Socio-Political Factors',
        'HR Manager - Build Relationships with Unions and Establish Communication Channels',
        'HR Manager - Conduct Collective Bargaining with Unions',
        'HR Manager - Collective Bargaining Agreement Reached?',
        'HR Manager - No',
        'HR Manager - Yes',
        'HR Manager - Roll Out Agreements and Policies',
        'HR Manager - Track Adherence to Agreements',
        'HR Manager - Grievances and Disputes Resolved?',
        'HR Manager - Agreements Implemented',
        'HR Manager - Disputes Resolved and Labour Relations Improved',
    ],

    'hr-1.20': [
        'Executives - BBBEE Cycle Initiated',
        'Executives - Analyse Current BBBEE Status and Identify Gaps Against Scorecard',
        'Board - Develop BBBEE Strategy and Action Plan',
        'Board - Board Approves BBBEE Strategy?',
        'Board - No',
        'Board - Yes',
        'HR - Implement BBBEE Initiatives Across All Scorecard Pillars',
        'HR - Collect and Compile Evidence for Verification',
        'HR - Submit to External Verification Agency',
        'HR - Verification Successful?',
        'HR - Yes',
        'HR - No',
        'HR - Report to Board and Monitor Progress',
        'HR - BBBEE Certificate Issued — Annual Cycle Complete',
        'HR - THIS PROCESS MAP IS BASED ON ASSUMPTIONS',
    ],

    'hr-1.21': [
        'HR - Organisational Design Cycle Initiated',
        'HR - Design New Organisational Structure',
        'Managers - Align Processes and Roles to New Structure',
        'Managers - Implement Organisational Changes',
        'Managers - Monitor and Refine Organisational Design',
        'Managers - Further Refinement Required?',
        'Managers - Yes',
        'Managers - New Organisational Structure Confirmed',
        'Managers - No',
    ],

    'hr-1.22': [
        'Line Managers - Complaint Received',
        'Line Managers - Receive and Note Complaint',
        'HR/Labour Lawyers - Investigate Disputes',
        'HR/Labour Lawyers - Formal Hearing Required?',
        'HR/Labour Lawyers - Conduct Disciplinary Enquiry / Hearing',
        'HR/Labour Lawyers - Yes',
        'HR/Labour Lawyers - Issue Verdict / Outcome',
        'HR/Labour Lawyers - Formal Hearing Required?',
        'HR/Labour Lawyers - Implement Sanction',
        'HR/Labour Lawyers - File Documents',
        'HR/Labour Lawyers - No',
        'HR/Labour Lawyers - No',
        'HR/Labour Lawyers - IR Case Closed — Documents Filed',
    ],

    // ----------------Finance------------------------
    'fin-1.1': [
        'CFO - Treasury Management Cycle Initiated',
        'CFO - Review and Approve Cash Flow Projections',
        'FM - Prepare Investment Recommendation Report(IRR)',
        'FM - Review IRR',
        'CFO - Is IRR Approved?',
        'FM - Perform Cash Transfer from Call Account to Chosen Investment Account',
        'FM - Retain Printout of Cash Investment Statement with Supporting Documentation',
        'FM - Investment Statement Retained — Audit Trail Complete',
    ],

    'fin-1.2': [
        'FA - Weekly Bank Statement Available',
        'FA - Compare Bank Statement to Pastel Cash Book',
        'FA - Identify and Record Reconciling Items',
        'FA - Submit Reconciliation to Financial Manager',
        'FM - Review and Sign Bank Reconciliation',
        'FM - Reconciling Items Present?',
        'FM - Assign Responsibility and Agree Action Plan',
        'FM - Track and Monitor Resolution of Reconciling Items',
        'FM - Prepare Cashbook Journal for Bank Charges',
        'FM - Review and Approve Bank Charges Journal',
        'MA - Process Adjusting Journal Entries',
        'MA - Approve Adjusting Journals',
        'MA - Perform Final Quality Check',
        'CFO - Sign-off on Bank Reconciliation',
        'CFO - Bank Reconciliation Finalised and Filed',
    ],

    'fin-1.3': [
        'FA - Payment Obligation Arises',
        'FA - Compile Payment Requisition',
        'FA - Payment made through various methods',
        'FA - Process payment details in Pastel',
        'FA - Payment made',
    ],

    'fin-1.4': [
        'MA - Monthly Interest Charge Cycle Initiated',
        'MA - Draw Interest Calculation as per the Term Agreement',
        'MA - Is KZNGFA Acting as Facility Agent?',
        'MA - Manually Calculate Interest on Spreadsheet',
        'FM / Credit Agent - Send Calculation and Supporting Documents to FM and Credit Agent for Review and Approval',
        'FM / Credit Agent - Interest Calculation Approved?',
        'FM / Credit Agent - Post Approved Entries onto the Loan Management System',
        'FM / Credit Agent - Generate Monthly Statements (Amortisation Table) for Customer',
        'FM / Credit Agent - Monthly Interest Cycle Closes',
    ],

    'fin-1.5': [
        'Financial Accountant - Dividends/Interest Payout Period Starts',
        'Financial Accountant - Confirm Incoming Fund on Bank Statement',
        'Financial Accountant - Posts Entries to General Ledger',
        'FM - Review Posted Entries',
        'FM - Are entries entered correctly?',
        'FM - Dividends/Interest Cycle Closes',
    ],

    'fin-1.6': [
        'MA - Fee Calculation Cycle Initiated',
        'MA - Manually Calculate the Relevant Fee',
        'FM - Submit Fee Calculation for Review and Approval',
        'FM - Fee Approved?',
        'CFO - Draw and Print Invoice for the Specific Fee',
        'CFO - Invoice Approved?',
        'CFO - Provide Approved Invoice to Customer',
        'CFO - Fee Cycle Closes',
    ],

    'fin-1.7': [
        'No SOP provided on other income procedures',
    ],

    'fin-2.1': [
        'Supplier/Requesting Employee - Invoice / Statement Received',
        'FA - Receive and Log Invoice in Supplier Inquiry Log',
        'FA - Verify or Create Supplier Masterfile',
        'FA - Supplier Masterfile Exists?',
        'FA - Submit Invoice to Requesting Employee for Service Verification',
        'FA - Create Supplier Masterfile',
        'Supplier/Requesting Employee - Sign Invoice as Evidence of Satisfaction',
        'FA - Prepare and Sign Payment Requisition Pack',
        'FM - Perform Initial Review of the Requisition Pack',
        'FM - Initial Review passed?',
        'FM - Perform Independent Quality Check',
        'MA - Quality Check Passed?',
        'CFO - CFO Approval Granted?',
        'CFO - Perform Final Review and Approve Payment Package',
        'CFO - Corrections Required',
        'CFO - Approved',
        'CFO - Payment Package Approved',
    ],

    'fin-2.2': [
        'Supplier / Delivery Agent - Movable Asset Delivered',
        'FA - Receive, Inspect and Verify Asset Against PO',
        'FA - Asset and Delivery Note Match PO?',
        'FA - Resolve',
        'FA - Tag New Asset with Label Before Allocation',
        'FA - Create Asset Record in Pastel Evolution',
        'MA - Reconcile CAPEX Forms and POs to Asset Information Forms',
        'MA - Reconciliation Confirmed?',
        'MA - CAPEX Asset Records Updated',
    ],

    'fin-3.1': [
        'FA - New Asset Acquired',
        'FA - Tag Asset and Create FAR Record',
        'FM - Reconcile CAPEX/PO Forms and Capture Asset in FAR',
        'FM - Engage Independent Assessor for Annual Revaluation',
        'CFO - Revaluation Figures Approved?',
        'FM - Inspect Asset Conditions for Impairment',
        'MA - Impairment Identified?',
        'MA - Update FAR with Approved Values and Update General Ledger',
        'CFO/SCM - Approve',
        'MA - Classify Assets and Generate Monthly Depreciation Batch',
        'MA - Perform Physical Verification and Resolve FAR Discrepancies',
        'MA - FAR Reconciled?',
        'MA - Identify Broken / Obsolete Assets and Prepare Disposal Form',
        'MA - Perform Physical Verification and Resolve FAR Discrepancies',
        'CEO/SCM - Follow SCM Process for Sale',
        'CEO/SCM - Asset Removed from FAR',
    ],

    'fin-4.1': [
        'Board - Planning and Budgeting Cycle Initiated',
        'Board - Complete Corporate Plan and Annual Performance Plan',
        'Department Managers - Estimate Departmental Costs Using OPEX and CAPEX Templates',
        'MA - Review, Consolidate and Resolve Departmental Budgets',
        'MA - Departmental Budget Discrepancies Resolved?',
        'MA - Consolidated KZNGFA Budget Submitted to CFO / Board',
    ],

    'fin-4.2': [
        'Executive Management - Resource Allocation Cycle Initiated',
        'Executive Management - Determine KZNGFA Corporate Objectives and Outcomes',
        'Board - Select Performance Indicators and Obtain Board Approval',
        'Board - Performance Indicators Approved by Board',
        'Board - Decide on Performance Targets and Obtain Board Approval',
        'Board - Performance Targets Approved by Board?',
        'Department Managers / FM / HR - Allocate Resources to Achieve Targets',
        'Department Managers / FM / HR - Resources Allocated Across Departments',
    ],

    'fin-4.3': [
        'CEO - In-Year Reporting Cycle Initiated',
        'CEO - Determine DEDT Reporting Deadlines',
        'CEO - Determine Format of Performance Reports',
        'CEO - Determine Schedule for In-Year Reporting',
        'CEO - Communicate Format and Schedule to All Managers',
        'Managers - Monitor and Analyse Performance on Ongoing Basis',
        'Managers - Performance Problems Identified?',
        'Managers - Take Corrective Action on Ongoing Basis',
        'Managers - Formal Measurement Point Due per Schedule?',
        'Managers - Formally Measure Performance When Due',
        'Managers - Evaluation and Reporting Cycle Complete',
    ],

    //INV and Post INV

    'inv-1.1.1': [
        'IO/IA - Business Partner Submits Application',
        'PA - Capture Prospect in CRM Pipeline Register',
        'CIO - Allocate Project to IO/IA',
        'CIO - Acknowledge Application by sending letter/email to BP',
        'CO - Is an NDA Required?',
        'LO - Review any amendments to NDA',
        'CO - Complete necessary credit checks on the applicant',
        'CO - Sends the list of FICA, KYC forms to BP',
        'CO - Completes probity checks',
        'IO/IA - Review information, Prepare Deal Discussion Paper, and make preliminary assessment',
        'IO/IA - Request minimum documentation from BP',
        'IO/IA - Was a response provided?',
        'IO/IA - Note to IRC As Lapsed Application',
        'IO/IA - Arrange for BP to make a presentation to Projectsco',
        'IO/IA - Proceed to Next Page',
        'IO/IA - Sign MOU with Potential Business Partner',
        'IO/IA - More time needed',
        'IO/IA - Park – 3 months/ until documentation received',
        'IO/IA - is missing documentation or new information?',
    ],

    'inv-1.1.2': [
        'PA - Request additional information if required by Projectsco',
        'IO/IA - Determine the economic/financial viability of the investment at a high level',
        'Projectsco - Discuss Merits of the Project with IO/IA',
        'IO/IA - Interact with BP to address Projectsco comments',
        'IO/IA - Updated deal discussion with a recommendation to either proceed to ISR or to decline',
        'Projectsco - ISR or Decline?',
        'Projectsco - Decline',
        'Projectsco - ISR',
        'IO/IA - Prepares letter/email to be sent to the BP',
        'IRC - Note to IRC and Applicant in 2 Weeks',
        'PA - Inform the PA to updated the project pipeline register.',
        'PA - Update Project Register Pipeline',
        'Deal Team - Share Deal Discussion Report with the Deal Team',
        'IO/IA - Alert Applicant about proceeding to next stage and arrange Site Visit',
        'IO/IA - Proceed to Next Page',
        'Risk - Does risk take any action?',
    ],

    'inv-1.1.3': [
        'IMO - Following site visit, additional information may be requested for ISR',
        'IMO - Prepare the ISR',
        'IMO - Prepare within 10 days',
        'IMO - Has 6 months lapsed since first probity check?',
        'CO - Verify probity checks have been completed in line with the requirements of the policies',
        'PA - Save a soft copy and file for all documents, Record the information on the Project register, Create a folder on the network directory',
        'PA - Update status of projects recorded in the register on Monthly Report/Quarterly',
        'IO/IA - Prepare a monthly/quarterly deal flow and project pipeline with help from the IO/IA',
        'IMO - Prepare the ISR with input from the IMO',
        'IRC - Approve, Decline or Defer?',
        'IRC - Proceed to DD stage',
        'IRC - Decline',
        'IRC - Send Decline Letter',
        'IRC - Proceed to Next Page',
        'IMO - Conduct high level probity check',
        'IMO - 2 working days',
        'IMO - Yes',
        'IMO - No',
    ],

    'inv-1.1.4': [
        'IO/IA - Contact BP on IRC Decision with email or letter',
        'IRC - Was it Approve or Defer?',
        'IRC - Defer',
        'IO/IA - Alert BP about Decision and possible restructring',
        'IRC - Approve',
        'BP - BP returns signed indicative term sheet',
        'IRC - Decline',
        'BP - Appeal of IRC decision to decline outright',
        'IO/IA - Submit amended ISR to IRC for approval',
        'IRC - Was the appeal successful?',
        'IRC - Rejected Application',
        'IRC - No',
        'IRC - Yes',
        'IRC - Decision',
        'IRC - Decline',
        'IRC - Proceed',
        'IRC - Proceed to DD',
        'IO/IA - Alert BP of Decline',
        'IO/IA - Close Application',
        'SCM - Advertise for DD External Provider',
        'SCM - Conduct Kick-Off meeting with DD Provider',
        'CO - Verify signed mandate letter and indicative term sheet have been received from the BP',
        'Service Provider - Perform DD',
        'Deal Team - Proceed to Next Page',
        'Deal Team - Does IRC get involved again or is with an amended deal discussion',
    ],

    'inv-1.1.5': [
        'IO/IA - Produce Final DD Report',
        'CO - Perform any further probity and FICA checks on applicant/BP for FAR',
        'Deal Team - Review DD',
        'Deal Team - Perform Commercial viability, Financial Viability, Taxation and ESG',
        'IMO - IMO conducts DD on Commercial risk and mitigants, Financial risk and mitigants, Pricing',
        'Legal - Legal conducts DD on Legality and regulatory universe, FICA and AML, Term sheet',
        'Deal Team - Prepare FAR, Risk Report, Legal Report and ESG Report',
        'Deal Team - Parallel IMO/IO to discuss the pricing',
        'IO/CIO - IO/CIO to sign-off the FAR before tabled at IRC',
        'Risk - Sign-off on risk and pricing report',
        'Risk - Sign-off Legal Report',
        'IO/CRO - IO/CRO sign-off ESG Report',
        'Deal Team - Continued',
    ],

    'inv-1.1.6': [
        'IRC - Analyse viability of project, quality of the FAR And Draft Sheet',
        'IRC - Provide Guidance to Deal Team',
        'IC - Recommend approval/decline of the FAR to the IC',
        'IC - Approval OR Decline?',
        'IC - Approval',
        'IC - Recommend to Board of Directors',
        'IC - Decline',
        'IC - Outright decline',
        'IC - Recommend to Board of Directors',
        'IO/IA - BP to be informed via offer letter and final term sheet',
        'IO/IA - Submit amended final term sheet to IRC for decision',
        'IO/IA - Submits amended final term sheet to IC for Decision recommended by IRC',
        'IO/IA - IO gives Term Sheet to BP for signature',
    ],

    'inv-1.2.1': [
        'CRO - Term Sheet Approved',
        'CRO - Lead Drafting of Loan Agreement and Security Documents',
        'IO/IMO - Provide Input on Draft Loan Agreement and Security Documents',
        'LO/Attorney - Verify Loan Agreement and Security Documentation Against Approved BoD Term Sheet',
        'IO/IMO - Provide Input on Reviewed Loan Agreement and Security Documents',
        'LO/Attorney - Communicate Required Changes to Attorneys',
        'CRO - Internal Version Satisfactory?',
        'IO/IMO - Share Pre-Execution Version of Loan Agreement with BP',
        'CRO - Yes',
        'CRO - Prepare Execution Version of Loan Agreement and Security Documents',
        'CEO - Sign Off Execution Loan Agreement and Security Documents',
        'CIO - Present and Execute Loan Agreement and Security Documents',
        'CIO - File Original Signed Loan Agreement and Security Documents in Safe Custody',
        'CIO - Prepare Monitoring Plan Before Disbursement',
        'IO/IMO - Collect and Verify Compliance with Conditions Precedent (CPs)',
        'IO/IMO - Confirm FICA Documents as Part of CP Verification',
        'CRO - Confirm CPs Satisfied to Borrower and Open Credit and Securities Files',
        'CFO/FA - Raise Invoice for Raising Fee (If Applicable)',
        'IO/IMO - Prepare Drawdown Input Sheet on Receipt of Borrower Drawdown Request',
        'CRO - Sign Off Disbursement Request and Submit to CFO',
        'CRO - Process Disbursement and Provide Proof of Payment',
        'CRO - Update Amortisation Schedule and Monitor Loan Utilisation and Repayments',
        'CRO - Funds Disbursed – Proceed to Monitoring',
    ],

    'inv-1.3.1': [
        'IMO - Funds Disbursed',
        'IMO - Prepare Monthly/Quarterly Client Performance Report',
        'IMO - Address Matters Highlighted After Reports or Site Visits',
        'IMO - Prepare Monthly/Quarterly Risk Profile Appraisal Report',
        'EA - Prepare Quarterly ESG Analysis and Progress Report',
        'EA - Request Annual Independent Asset Valuation',
        'CFO - Send Reminder of Payments and Information Undertakings Due to Client',
        'CO - Notify Client of Change in Interest Rate',
        'CFO - Payment Received on Due Date?',
        'CFO - Yes',
        'CFO - Save Client Information and Update Records',
        'CFO - Has payment been received?',
        'CFO - No',
        'CFO - Proceed to default management',
        'CFO - Sign Off Verification of Full Repayment and Close Client Files',
        'CFO - Release Securities and Update Project Register',
        'CO - Ensure Personal Information Treated Per Document Management Policy and Relevant Legislation',
        'CO - Loan Fully Repaid – Post Investment Process Complete',
        'CFO - Yes',
    ],

    'inv-1.3.2': [
        'IMO - Default Event Identified',
        'IMO - Compile Default Listing and Amortisation Schedule',
        'IMO - Notify IO and CRO of Default in Writing',
        'IMO - Arrange Client Meeting and Open Diary Card',
        'MA - Submit Rectification Report and Update Client Credit File',
        'IRC - Client Keeps Arrangement?',
        'IRC - No',
        'IRC - Escalate Default and Impose Penalty Interest',
        'MA - Yes',
        'MA - Account Normalised',
        'IRC - Risk Classification and Provision',
        'IMO - Payment Made in which timeframe?',
        'IMO - >30 <60 Days',
        'IMO - Conduct Site Visit; Prepare Restructuring Proposal and Watchlist',
        'IMO - >60 <90 Days',
        'IMO - Issue Letter of Demand Under CEO Signature; Prepare Restructuring Proposal and Watchlist',
        'IMO - >90 Days',
        'IMO - Issue Final Notice; Assess Loan Saleability; Submit Handover List to IC/Board',
        'Board - Continued',
        'IMO - Account Normalised',
    ],

    'inv-1.3.2b': [
        'IMO - Is Restructuring Agreed or Account Rectified?',
        'IMO - No: Goes back to Step 6 (Escalate Default and Impose Penalty Interest)',
        'IMO - Agreed',
        'IMO - Handed Over/Account Sold to 3rd Party debt collector',
    ],

    'inv-1.3.3': [
        'IMO - Legal Recovery Initiated',
        'IMO - Review Securities File and Confirm Security Documentation Ready for Perfection',
        'CRO - Review Securities File and Confirm Security Documentation Ready for Perfection',
        'Legal - Review Securities File and Confirm Security Documentation Ready for Perfection',
        'Legal - Prepare Needs Analysis for Appointment of Service Providers',
        'CFO - Recommend and Appoint Liquidators',
        'Legal - Liaise with Attorneys to Explore Recovery Options',
        'Legal - Brief Valuators on Property to Be Evaluated',
        'CFO - Recommend and Appoint Liquidators',
        'CFO - Liaise with Liquidators to Maximise Break-Up Value',
        'BoD - Submit Proof of Claims to Liquidator',
        'BoD - Provide Legal Status Update on Recoverability',
        'CFO - Prepare Write-Off Report for IC and ARC',
        'BoD - Write-Off Approved by BoD?',
        'CFO - Provide Approved Write-Off Schedule to CFO for Action',
        'BoD - Yes',
        'BoD - No',
        'CFO - Write-Off Actioned',
    ],

    'inv-2.1.1': [
        'IO/IA - Business Partner Submits Application',
        'PA - Capture Prospect in CRM Pipeline Register',
        'PEO - Allocate Project to IO/IA',
        'IO/IA - Review Information and Conduct Preliminary Assessment',
        'IO/IA - Sign MOU with Potential Business Partner',
        'IO/IA - 3 working days',
        'IO/IA - Sufficient Merit to Proceed with Screening?',
        'IO/IA - Issue Decline Letter',
        'IO/IA - Deal Closed',
        'IO/IA - Yes',
        'IO/IA - Issue Engagement Letter to Business Partner',
        'IO/IA - Arrange Presentation or Initial Screening Meeting',
        'CO - Perform Probity Check on Business Partner',
        'IO/IA - Prepare ISR Including Indicative High-Level Term Sheet',
        'PA - Update Status of Projects on Pipeline Register',
        'PEO - Update Status of Projects on Pipeline Register',
        'IRC - IRC Decision — Approve, Defer, or Decline?',
        'IRC - Decline',
        'IRC - Defer',
        'IRC - Issue Decline Letter',
        'IRC - Deal Closed',
        'IRC - Approve',
        'IRC - Issue DD Commencement Letter to Business Partner',
        'IRC - Continued',
    ],

    'inv-2.1.2': [
        'IRC - Ensure DD Team Actions the DD Plan',
        'PEO - Revise Term Sheet Based on DD Findings',
        'PEO - Signed Revised Term Sheet Received?',
        'IO/IA - Prepare FAR incorporating revised term sheet, FAR risk report, FAR legal report, and FAR ESG report',
        'IRC - Yes',
        'IRC - No',
        'IRC - Present FAR with Recommendation and Revised Term Sheet at IRC',
        'IRC - IRC Recommends FAR for Submission to EIC?',
        'IRC - Submit FAR Decision Pack to Cosec',
        'Cosec - 7 Days Before EIC Meeting',
        'EIC/BoD - Review FAR Decision Pack',
        'EIC/BoD - EIC Decision — Approve, Decline, or Refer Back?',
        'EIC/BoD - Defer',
        'PEO - Inform Business Partner of Deferral and How to Reconstruct Proposal',
        'IO/IA - IO prepares decline letter',
        'EIC/BoD - Outright Decline',
        'PEO/CIO - Issue Offer Letter and Final Term Sheet to Business Partner',
        'PEO/CIO - FAR Approved — Proceed to Equity Contracting and Disbursement',
    ],

    'inv-2.2.1': [
        'CFO - EIC Approval Received — Contracting Initiated',
        'CFO - Draft Equity Agreements and Security Documents',
        'GLC - Verify Equity Agreements Against Approved EIC Term Sheet',
        'PEO/CIO - Issue Internal Memo on Execution Versions',
        'PEO/CIO - Agreements Approved for Execution?',
        'CFO - Yes',
        'CFO - Prepare Repayment Schedule Where Applicable',
        'PEO/CIO - Submit Final Execution Agreement to CEO for Sign-Off',
        'IO/IA - Verify Compliance with CP List',
        'PEO/CIO - Agreements Approved for Execution?',
        'IO/IA - No',
        'IO/IA - Yes',
        'IO/IA - Receive Disbursement Request from Sponsor / Investee',
        'Fund Administrator - Issue Disbursement Instruction to Fund Administrator',
        'Fund Administrator - Issue Drawdown Notice',
        'Fund Administrator - Sign Confirmed Notice of Drawdown and Process Disbursement',
        'Fund Administrator - 15 Business Days Prior to Payment Date',
        'Fund Administrator - Disbursement Processed',
    ],

    'inv-2.3.1': [
        'ESG - Disbursement Complete — Post Investment Activities Initiated',
        'CIO/PEO - Assess Investee Company and Constitute Board of Trustees',
        'IO/IA - Implement 180-Day Action Plan as Per FAR Approval',
        'IO/IA - Prepare Quarterly Review Report of Investee Company',
        'ESG - Prepare Separate ESG Analysis and Progress Report',
        'ESG - Quarterly',
        'IRC - IRC Provides Comments on Quarterly Reports',
        'IO/IA - Conduct Internal Valuation of Investee Company',
        'IO/IA - Quarterly',
        'IO/IA - Commission Independent Valuation',
        'IO/IA - Annual or When Needed',
        'IRC - Review FAR Exit Strategy and Assess Portfolio Company Performance',
        'EIC - Investee Company Ready for Exit?',
        'EIC - No',
        'EIC - Prepare Investee Company for Exit',
        'EIC - Yes',
        'EIC - Write Exit Paper for EIC Review',
        'EIC - EIC Approves Exit Strategy and Paper?',
        'EIC - No',
        'EIC - Yes',
        'EIC - Exit Approved',
    ],
    //COSEC
    'cosec-1.1': [
        'CoSec - Monthly Meeting Cycle Initiated',
        'CoSec - Circulate Meeting Notice',
        'EXCO - Prepare and Circulate Agenda',
        'CoSec - Circulate Matters Arising for Update',
        'CoSec - Circulate Minutes from Previous Meeting for Review',
        'CoSec - Consolidate Committee Reports',
        'CoSec - Upload Reports to iBoardpapers',
        'CoSec - Circulate Matters Arising',
        'CoSec - Arrange Logistics for Meetings',
        'CS Intern - Capture Attendance',
        'CS Intern - Review and Draft Meeting Minutes',
        'Chairperson - Sign Meeting Minutes',
        'CoSec - Develop Resolution Extracts',
        'CoSec - Update Matters Arising Tracker',
        'CoSec - Update Resolutions Register',
        'CoSec - Maintain Statutory Records and Charters',
        'CoSec - Cycle Complete',
        'Board - Hold Board Meeting',
    ],

    'cosec-1.2.1': [
        'CoSec - Annual Work Planning Cycle Initiated',
        'CoSec - Review and Develop Work Plan to Align to Committee Mandate',
        'CoSec - Table and Adopt Work Plan',
        'Departments - Report Against Work Plan',
        'Departments - Reports Submitted to Committees',
        'Departments - Quarterly',
    ],

    'cosec-1.2.2': [
        'CoSec - Quarterly Planning Cycle',
        'CoSec - Track and Update Work Plan Progress',
        'Departments - Report Content Submitted to CoSec',
        'CoSec - Consolidate Report and Upload to iBoardPapers',
        'Committees - Reporting Cycle Concludes',
        'CoSec - Table Report to Relevant Department',
    ],

    'cosec-1.3': [
        'CoSec - 2 Year Charter Review Initiated/As Needed',
        'CoSec - Develop or Review Charter',
        'EXCO - Table Charter to EXCO for Review',
        'Board - Charter is adopted by board',
        'Board - Table to Board',
        'EXCO - Is the Charter Approved?',
        'EXCO - Yes',
        'EXCO - No',
        'Board - Is the Charter Approved?',
        'Board - Yes',
        'Board - No',
    ],

    'cosec-1.4': [
        'CoSec - 2 Year Policy Review Initiated/Legislature Change',
        'CoSec - Develop or Review Policy',
        'EXCO - Table Policy to EXCO for Review',
        'Board - Policy is adopted by board',
        'Board - Table to Board',
        'EXCO - Is the Policy Approved?',
        'EXCO - Yes',
        'EXCO - No',
        'Board - Is the Policy Approved?',
        'Board - Yes',
    ],

    'cosec-1.5': [
        'MEC - Board Appointment Initiated',
        'CoSec - Board Appointment',
        'CoSec - Welcome and Introduce Board',
        'CoSec - Extract Member Details and Develop Skills Profile / Committee Assignment Schematic',
        'CoSec - Prepare Memo Recommending Committee Placement',
        'CoSec - Schedule and Host Committee Constitution Meeting',
        'CoSec - Parallel Schedule Induction',
        'EXCO - Liaise with EXCO and Share Governance Documents',
        'CoSec - Arrange Logistics',
        'EXCO - Host Induction and Present',
        'EXCO - Board Members Successfully Inducted',
    ],

    'cosec-2.1': [
        'Board/Committee - Opinion Paper Request Received',
        'CoSec - Note Request of Opinion Paper From Meeting',
        'CoSec - Conduct Research with Relevant Departments as Needed',
        'CoSec - Prepare Opinion Paper',
        'CoSec - Schedule and Host Committee Constitution Meeting',
        'EXCO - Table Opinion Paper for Support',
        'EXCO - Is the Policy Approved?',
        'EXCO - No',
        'EXCO - Table Paper at Relevant Committee and Board for Adoption',
        'Board/Committee - Opinion Paper Adopted',
    ],

    //PMO
    'pmo-1.1': [
        'Business Unit / Project Sponsor - Project Need Identified',
        'Project Manager - Appoint the PM Office – DOA To be shared for thresholds',
        'Project Manager - Develop Project Charter',
        'Project Manager - Kick-Off Meeting to discuss Project Charter',
        'Project Manager - Develop Project Plan to be used as a tracker',
        'Project Manager - Project plan is developed',
        'Project Manager - Develop Memo that will be sent to EXCO',
        'Project Manager - Project Execution',
        'Project Manager - Present to EXCO',
        'Steering Committee - Project Memo, or any supporting addendums Approved?',
        'Steering Committee - Yes',
        'Steering Committee - No',
        'Project Manager - Develop Project Risk Register',
        'Project Manager - Monitoring',
        'Project Manager - Prepare Monthly Project Status Report(Memo)',
        'Project Manager - Review Monthly Project Status Report',
        'Project Manager - Major Risks or Issues Identified?',
        'Project Manager - No',
        'Project Manager - Implement Corrective Actions',
        'Project Manager - Prepare Project Closure Report',
        'Steering Committee - Presented to committee and Committee will recommend',
        'Project Manager - Project Closed',
        'Steering Committee - Project Charter Approved?',
        'Steering Committee - Yes',
        'Steering Committee - No',
    ],

    'pmo-1.2': [
        'Finance - Relocation Directive',
        'Project Manager - Initiate Office Relocation Project',
        'Project Manager - Define Scope and requirements',
        'Project Manager - Coordinate stakeholder consultations',
        'Finance - Budget Approved?',
        'Project Manager - Developed implementation plan',
        'Project Manager - Conduct Due Diligence on the Site',
        'Project Manager - Coordinate Office Relocation Activities',
        'Project Manager - Conduct Post-Implementation Review',
        'CEO - Relocation Project Completed',
    ],

    'pmo-1.3': [
        'Project Manager - EXCO Governance Cycle Initiated',
        'Project Manager - Develop and Maintain Annual EXCO Meeting Calendar',
        'Project Manager - Draft Memo that is used for EXCO submission',
        'Project Manager - Submit EXCO Agenda Items and Supporting Documents',
        'CEO - Is Agenda approved?',
        'Project Manager - Yes',
        'Project Manager - Consolidate and Combine Agenda',
        'Project Manager - Share Agenda with Departments',
        'Project Manager - Compile and Distribute EXCO Meeting Pack',
        'Project Manager - Chair EXCO Meeting',
        'Project Manager - Capture Attendance and Meeting Minutes',
        'Project Manager - Maintain EXCO Document Repository',
        'Project Manager - Develop EXCO Resolution Action Tracker',
        'Project Manager - Implement and Monitor EXCO Decisions',
        'Project Manager - Develop EXCO Resolution Action Tracker',
        'Project Manager - Updates Feed into Next EXCO Cycle',
        'CEO - CEO Reviews Agenda',
        'CEO - No',
        'CEO - Is CEO Available to chair the meeting?',
        'CEO - Yes',
        'CEO - Appoint an acting chairperson',
        'CEO - No',
    ],

    'pmo-1.4': [
        'Project Manager - Integrated Reporting Cycle Initiated',
        'Project Manager - Develop Integrated Reporting Project Plan and Timeline',
        'SCM - Drafting of RFQ/RFP',
        'Service Provider - Appoint service provider',
        'Service Provider - Kick-Off with Service provider plan and ways of working',
        'Finance - Confirm Needs analysis',
        'Finance - Develop Needs Analysis',
        'Project Manager - Coordinate Drafting of Integrated Report',
        'Service Provider - Draft the integrated report',
        'Project Manager - QA to ensure satisfaction',
        'EXCO/Board - EXCO revises and recommends to board for approval',
        'Board - Board Approves?',
        'Board - Yes',
        'Board - No',
        'Project Manager - Integrated report is published',
        'Project Manager - Integrated Report Published',
    ],

    'pmo-1.5': [
        'Project Manager - APP Governance Cycle Initiated',
        'Project Manager - Coordinate APP Submissions from Business Units',
        'Project Manager - Align APP with Organisational Strategy and Shareholder Priorities',
        'Project Manager - Validate Performance Indicators and Targets',
        'Project Manager - Consolidate APP for EXCO and Board Approval',
        'EXCO/Board - APP Approved?',
        'EXCO/Board - No',
        'EXCO/Board - Yes',
        'Project Manager - Monitor Quarterly APP Performance',
        'Finance - Maintain APP Performance Dashboard',
        'Project Manager - Coordinate APP Performance Reporting to Governance and Shareholders',
        'Project Manager - Facilitate APP Review and Improvement Planning',
        'Project Manager - Integrated Report Published',
    ],

    'pmo-1.6': [
        'Project Manager - Organisational Performance Monitoring Cycle Initiated',
        'Project Manager - Develop Organisational Performance Reporting Calendar',
        'Business Units / Departments - Collect Monthly and Quarterly Performance Data',
        'Business Units / Departments - Validate Performance Evidence',
        'Business Units / Departments - Analyse Performance Data Against Targets',
        'Business Units / Departments - Prepare Monthly Dashboards and Quarterly Reports',
        'Business Units / Departments - Performance Monitoring Cycle Completed',
    ],

    'pmo-1.7': [
        'Project Manager - Strategic Planning Cycle Initiated',
        'Project Manager - Develop Organisational Strategic Planning Calendar',
        'Project Manager - Coordinate Strategic Planning Workshops and Stakeholder Engagements',
        'Business Units / Departments - Submit Strategic Initiatives and Departmental Inputs',
        'Project Manager - Develop Organisational Strategic Implementation Roadmap',
        'Project Manager - Monitor Progress Against Strategic Objectives and Milestones',
        'Project Manager - Strategy Governance Cycle Completed',
        'Project Manager - Facilitate Strategic Performance Review Sessions',
        'Project Manager - Coordinate Periodic Strategy Reviews and Updates',
    ],

    'pmo-1.8': [
        'PMO - Still needs to be decided on by PMO',
    ],

    //Marketing
    'mkt-1.1': [
        'Marketing and Communications Manager - Monthly Post Date',
        'Marketing and Communications Manager - Create Content Calendar',
        'Service Provider/Agency - Develop Social Media Content',
        'Marketing and Communications Manager - Review Content',
        'Marketing and Communications Manager - Was Content Approved?',
        'Marketing and Communications Manager - Yes',
        'Marketing and Communications Manager - Publish and Schedule Posts',
        'Marketing and Communications Manager - Monitor Engagement',
        'Marketing and Communications Manager - Handle Negative Interactions',
        'Marketing and Communications Manager - Generate Performance Analytics Report',
        'Marketing and Communications Manager - Performance Report Delivered',
        'Marketing and Communications Manager - No',
    ],

    'mkt-1.2': [
        'Marketing and Communications Manager - Initiative requiring campaign',
        'Marketing and Communications Manager - Define Campaign Goals',
        'Marketing and Communications Manager - Identify Campaign Stakeholders',
        'Marketing and Communications Manager - Needs Analysis is created',
        'Finance - Needs analysis Approved?',
        'Finance - Yes',
        'Finance - Allocation of funds for scope outlined in Needs Analysis',
        'Marketing and Communications Manager - Was content Approved?',
        'Marketing and Communications Manager - Yes',
        'Marketing and Communications Manager - Launch Campaign',
        'Marketing and Communications Manager - Monitor Campaign Performance',
        'Marketing and Communications Manager - Review Campaign Impact',
        'Marketing and Communications Manager - Evaluate Campaign Results',
        'Marketing and Communications Manager - Campaign Closed — Reports Delivered to Management',
        'Service Provider/Agency - Develop Campaign Content',
        'Service Provider/Agency - No',
    ],

    'mkt-1.3': [
        'Marketing and Communications Manager - Organisational Update / News Event Occurs',
        'Marketing and Communications Manager - Draft Press Release',
        'Relevant Department Head (Including Chairperson of Board) - Review Media Materials',
        'Relevant Department Head (Including Chairperson of Board) - Materials Approved?',
        'Relevant Department Head (Including Chairperson of Board) - No',
        'Marketing and Communications Manager - Distribute Press Release',
        'Marketing and Communications Manager - Yes',
        'Marketing and Communications Manager - Track Media Mentions',
        'Marketing and Communications Manager - Respond to Media Inquiries, it might need interview',
        'Marketing and Communications Manager - Proactive Media Management',
        'Marketing and Communications Manager - Media Monitoring',
        'Marketing and Communications Manager - Media Cycle Complete',
    ],

    'mkt-1.4': [
        'Marketing and Communications Manager - Event Set',
        'Marketing and Communications Manager - Status Meeting(Event planned) – External SP involved',
        'Marketing and Communications Manager - Conduct Needs Analysis',
        'Finance Manager - Confirms the Needs Analysis',
        'Marketing and Communications Manager - Coordinate Vendors',
        'Marketing and Communications Manager - Communicate and Promote Event',
        'Marketing and Communications Manager - Minimum Registrations Met?',
        'Marketing and Communications Manager - No',
        'Marketing and Communications Manager - Execute Event',
        'Marketing and Communications Manager - Collect Feedback from Participants',
        'Marketing and Communications Manager - Event Complete',
        'SCM Manager - Source the supplier',
        'SCM Manager - Handle logistics',
    ],

    'mkt-1.5': [
        'Marketing and Communications Manager - Item to be monitored Is launched',
        'Marketing and Communications Manager - Set Monitoring Objectives',
        'Marketing and Communications Manager - Collect Media Mentions',
        'Marketing and Communications Manager - Conduct Sentiment Analysis',
        'Marketing and Communications Manager - Generate Monitoring Report',
        'Marketing and Communications Manager - Adjust Communication Strategy',
        'Marketing and Communications Manager - Strategy Adjustment Required?',
        'Marketing and Communications Manager - Yes',
        'Marketing and Communications Manager - Strategy Updated',
        'Marketing and Communications Manager - No',
        'Marketing and Communications Manager - Monitoring Cycle Complete',
    ],

    'mkt-1.6': [
        'Marketing Manager - Brand Strategy Cycle Initiated',
        'Marketing Manager - Conduct Market Research',
        'Marketing Manager - Define Brand Positioning',
        'Marketing Manager - Develop Brand Messaging',
        'Marketing Manager - Messaging Aligned to Brand Guidelines?',
        'Marketing Manager - Yes',
        'Marketing Manager - No',
        'Marketing Manager - Create Visual Identity Guidelines',
        'Marketing Manager - Conduct Brand Audits',
        'Marketing Manager - Brand Audit Satisfactory?',
        'Marketing Manager - Yes',
        'Marketing Manager - Monitoring Cycle Complete',
        'Marketing Manager - No',
    ],

    'mkt-1.7': [
        'Marketing Manager - Communication Need Identified',
        'Marketing Manager - Define Campaign Goals',
        'Marketing Manager - Develop Campaign Messaging',
        'Finance - Approve Needs analysis',
        'Marketing Manager - Create Campaign Materials',
        'Marketing Manager - Materials Approved?',
        'Marketing Manager - Yes',
        'Marketing Manager - Launch Campaign',
        'Marketing Manager - Monitor Campaign Performance',
        'Marketing Manager - Evaluate Campaign Results',
        'Marketing Manager - Campaign Goals Achieved?',
        'Marketing Manager - Yes',
        'Marketing Manager - Campaign Closed',
        'Marketing Manager - No',
        'SCM - Help with developing RFQ for catering needs etc',
        'SCM - Phase',
    ],

    //Risk
    'risk-1.1': [
        'Risk & Compliance - Project Application Submitted',
        'IO/Deal Team - Project Screening & Committee Referral',
        'IO/Deal Team - Arrange Site Visit',
        'IO/Deal Team - Prepare ISR',
        'IO/Deal Team - Is information gathered from probity checks sufficient?',
        'IO/Deal Team - No',
        'IO/Deal Team - Provide further information',
        'Risk & Compliance - Risk Identification & Compliance Checks',
        'IO/Deal Team - Yes',
        'IO/Deal Team - Proceed to Due Diligence and Appoint Suppler',
        'IO/Deal Team - Prepare FAR',
        'IRC - IRC Review?',
        'IRC - Decline',
        'Deal Team - Deal Team Revises FAR',
        'IRC - Approval',
        'IC - Final Approval Decision',
        'IC - Approve/Decline?',
        'IC - Approval',
        'BoD - Term Sheet Finalisation',
        'Legal - Sign Term Sheet',
        'Legal - Agreement Drafting & Signing',
        'Legal - Deal Agreements Finalised',
    ],

    'risk-1.2.1': [
        'Legal Officer - Security Documents Signed',
        'Legal Officer - Confirm Signed Security Documents',
        'Post Inv Monitoring Department - Prepare CP detailed checklist',
        'IO - Send Checklist to Client',
        'Client - Submits Required Documents',
        'Compliance Analyst - Verify FICA Compliance',
        'Compliance Analyst - Are FICA Documents Compliant?',
        'Compliance Analyst - Alert Client to Resubmit Documents',
        'Compliance Analyst - No',
        'Compliance Analyst - Yes',
        'Compliance Analyst - CP Sign-Off',
        'Post Inv Monitoring Department - Prepare Monitoring Report Template',
        'Post Inv Monitoring Department - Share Monitoring Template With Client',
        'Post Inv Monitoring Department - Financial Close, Proceed to Disbursement',
    ],

    'risk-1.2.2': [
        'Client - Security Documents Signed',
        'IO - Receive Disbursement Request',
        'IO - Advise CFO of Disbursement Request',
        'CRA - Prepare Disbursement Pack',
        'CRA - Collate Supporting Information',
        'CRA - Circulate Disbursement Pack for Approval',
        'Executive Signatories - CEO Final Sign-Off',
        'CRA - File Signed Disbursement Pack',
        'CRA - Submit Signed Pack to CFO',
        'CRA - Disburse Funds',
        'CRA - Type of Disbursement',
        'CRA - First',
        'CRA - Fund Disbursed',
        'CRA - Prepare Use of Funds Reconciliation',
        'CRA - Subsequent',
        'CRA - Verify Use of Funds Schedule',
        'IO - Verify Authorised Signatories',
    ],

    'risk-1.3': [
        'Monitoring Office - Quarterly Monitoring Cycle Initiated',
        'CRA - Prepare Portfolio Quarterly Report',
        'CRA - Reconcile Disbursements',
        'CRA - Is the project still in construction phase?',
        'CRA - Yes',
        'IO - Conduct Monthly Site Visits',
        'IO - Monthly',
        'IO - Conduct Quarterly Site Visits',
        'IO - Quarterly',
        'CRA - No',
        'CRA - Prepare Portfolio Quarterly Report',
        'Risk Commitee - Present Portfolio Report',
        'Risk Commitee - Conduct Risk Grading',
        'Risk Commitee - Report Risk Reclassification',
        'SCM - Send Monthly Amortisation Schedule',
        'SCM - Send Payment Reminder',
        'SCM - Create Monitoring Report',
        'SCM - Monitor Cycle Completed',
    ],

    'risk-1.4': [
        'Risk Department - Restructuring Interventions Failed',
        'Risk Department - Receive Project Security Documentation',
        'Risk Department - Prepare Recovery Recommendations',
        'Committees - Approve Recovery Strategy',
        'Legal - Initiate Legal Appointment Process',
        'SCM - Appoint Service Provider',
        'Service Provider - Conduct Briefing Session',
        'Risk Department - Prepare Risk Recovery Report',
        'Risk Department - Review Risk Recovery Report',
        'Risk Department - Submit Report To Committees',
        'Committees - Store Report',
        'Committees - Recovery Process Initiated',
    ],

    'risk-2.1': [
        'IO - Opportunity Identified',
        'IO - Does Applicant Require NDA?',
        'IO - Yes',
        'IO - Request NDA Draft from Legal',
        'Legal - Provide NDA Draft',
        'Legal - Approve NDA for Execution',
        'Legal - NDA Signed by Both Parties',
        'IO - No',
        'IO - Proceed to straight to screening',
    ],

    'risk-2.2': [
        'IO - Deal Received',
        'IO - Begin ISR Preparation',
        'Legal Officer - Prepare Preliminary Legal Risk Report',
        'Legal Officer - Identify Legal Risks Associated with Project',
        'Legal Officer - Document Legal Risk Findings & Recommendations',
        'Legal Officer - Draft Indicative Term Sheet',
        'Legal Officer - Submit Legal Risk Report & Term Sheet to IO',
        'IO - ISR Inputs Complete',
    ],

    'risk-2.3': [
        'IO - DD Service Provider Investigation Complete',
        'IO - Receive and Review Final DD Report',
        'IO - Prepare FAR',
        'Legal Officer - Submit Final Legal Due Diligence Report',
        'IO - Consolidate FAR Including Legal, ESG and Credit Risk Reports',
        'IO - Submit Consolidated FAR Package to IRC',
        'IRC - IRC Recommends Approval?',
        'IRC - Attend to Queries and Adverse Findings',
        'IRC - No',
        'IRC - Yes',
        'IC - Present FAR to Investment Committee for Approval',
        'IC - IC Approves Project?',
        'IC - No',
        'IC - Yes',
        'BoD - Submit Approved FAR to BoD for Final Confirmation',
        'BoD - BoD Approves?',
        'BoD - No',
        'BoD - Yes',
        'BoD - Project Approved by BoD',
    ],

    'risk-2.4': [
        'Legal Officer - BoD Approval',
        'Legal Officer - Finalise Term Sheet Including Approval Conditions',
        'Client - Client Accepts Term Sheet?',
        'Legal Officer - Send Term Sheet to Client for Signature',
        'Legal Officer - No',
        'Legal Officer - Yes',
        'Client - Draft Legal Agreement',
        'Client - Review and Negotiate Agreement Terms',
        'Legal Officer - Sign Agreements with all parties',
        'Legal Officer - Issue Conditions Precedent Schedule to Client',
        'Client - Submit Conditions Precedent Documents',
        'Legal Officer - Issue CP Satisfaction Notice',
        'Legal Officer - CPs Verified',
    ],

    'risk-2.5': [
        'IO - Breach of Agreement Identified',
        'IO - Notify Legal of Breach',
        'Legal Officer - Draft and Issue Letter of Demand',
        'IO - Assess Response to Letter of Demand',
        'IO - Solution Reached?',
        'IO - Yes',
        'IO - Breach resolved, Monitoring Continues',
        'IO - No',
        'IO - Exhaust All Alternatives',
        'IO - Recommend Litigation / Business Rescue / Liquidation to IRC, IC then BOD',
        'IRC - Committees Approve Enforcement Action',
    ],

    'risk-2.6': [
        'IO - Enforcement Action Approved by Committees',
        'IO - Hand Over Project Security Documentation to Legal',
        'Legal Officer - Reccomend Recovery Avenues as Approved by Committees',
        'SCM - Appoint Service Provider(Attorney, Liquidator or Sheriff)',
        'Service Provider - Hold Briefing Session with Service Provider',
        'Service Provider - Implement BoD Resolution',
        'Legal Officer - Draft Legal Report for Submission to Various Committees',
        'Legal Officer - Legal Report Submitted to Various Committees',
    ],

    'risk-3.1.1': [
        'CO - Regulatory Compliance Cycle Initiated',
        'CO - Establish Regulatory Universe Rated in Order of Importance',
        'CO - Establish Compliance Checklist (Questionnaire) Covering Critical Sections of Acts',
        'CO - Monitor Changes to Regulations',
        'CO - Update Regulatory Universe and Checklist',
        'CO - Align Updates with Departments\' Legal Documentation',
        'CO - Train and Socialise Regulation Prescripts',
        'CO - Regulatory Universe and Checklist Updated',
    ],

    'risk-3.2': [
        'CO - Policy Compliance Cycle Initiated',
        'CO - Establish policy universe',
        'CO - Ensure Policies Updated Within Prescribed Timeframes',
        'CO - Provide Policies to Each Department',
        'CO - Report on Non-Compliance of Policies Quarterly',
        'CO - Train and Socialise Policies with Departments',
        'CO - Policy Compliance Cycle Complete',
    ],

    'risk-4.1': [
        'Risk Officer - Enterprise-level Risk Identified',
        'Risk Officer - Describe the Nature of Risk',
        'Risk Officer - Assess Probability of Risk Occurring',
        'Risk Officer - Evaluate and Qualify Risks Identified',
        'Risk Officer - Determine Mitigations and Controls for Each Risk',
        'Risk Officer - Monitor Changes to Risk Levels and Execution Against Mitigations and Controls',
        'Risk Officer - Add to Quarterly Report',
        'Risk Officer - Risk Reported On',
    ],

    'risk-5.1': [
        'Requesting Department - Legal Opinion Need Identified',
        'Requesting Department - Hold Meeting to Discuss Legal Matter',
        'Requesting Department - Legal Opinion Required?',
        'Requesting Department - Yes',
        'Requesting Department - Request Legal Opinion from Department Head and Head of Legal',
        'Head of Legal - Assess Nature of Request',
        'Head of Legal - Internal or External Service Provider?',
        'Head of Legal - External',
        'Requesting Department - Develop Needs Analysis and Shares with CRO',
        'CRO - CRO Approves Needs Analysis?',
        'Finance - Accepted',
        'Finance - Approve Funds for External Legal Opinion',
        'SCM - Follow SCM Process Until Appointment',
        'CRO - Rejected',
        'Head of Legal - Internal',
        'Head of Legal - Appoint Internal Legal for Provision of Opinion',
        'Head of Legal - Present Legal Opinion to Requestor or Committee',
        'Head of Legal - Further Clarity Needed?',
        'Head of Legal - Yes',
        'Head of Legal - No',
        'Head of Legal - Legal Opinion Process Complete',
    ],

    'risk-5.2': [
        'Requesting Department - Policy Update Cycle Inititated',
        'Requesting Department - Hold Meeting to Discuss Legal Matter',
        'Requesting Department - Policy Drafting Required?',
        'Requesting Department - Yes',
        'Requesting Department - Request Policy Update from Department Head and Head of Legal',
        'Head of Legal - Assess Nature of Request',
        'Head of Legal - Internal or External Service Provider?',
        'Head of Legal - External',
        'Requesting Department - Develop Needs Analysis and Shares with CRO',
        'CRO - CRO Approves Needs Analysis?',
        'Finance - Accepted',
        'Finance - Approve Funds for External Policy Drafting',
        'SCM - Follow SCM Process Until Appointment',
        'CRO - Rejected',
        'Head of Legal - Internal',
        'Head of Legal - Appoint Internal Legal for Drafting of Policy',
        'Head of Legal - Present Updated Policy to Requestor or Committee',
        'Head of Legal - Further Clarity Needed?',
        'Head of Legal - Yes',
        'Head of Legal - Policy Draftimg Process Complete',
        'Head of Legal - No',
    ],

    'risk-5.3.1': [
        'SCM - Drafting Request Received',
        'SCM - Escalate Request to Legal and Share Minimum Documents',
        'Legal Officer/Intern - Draft SLA and Clarify with SCM if Needed',
        'Legal Officer/Intern - Share Draft with SCM',
        'Legal Officer/Intern - Share Draft with Service Provider for Comments',
        'Legal Officer/Intern - Service Provider Happy with Draft?',
        'Line Department - Yes',
        'Line Department - Load Document on Doxit for CEO to Sign',
        'CEO - Sign Updated Version on Doxit',
        'CEO - SLA Fully Executed',
        'Legal Officer/Intern - No',
        'Legal Officer/Intern - Determine Whether to Accept or Negotiate Comments',
        'Legal Officer/Intern - Agreement Reached on Comments?',
        'Legal Officer/Intern - No',
        'Legal Officer/Intern - Yes',
        'Legal Officer/Intern - Notify Service Provider of Decision on Comments',
    ],

    'risk-5.3.2': [
        'Line Department - Need for MOU, NDA or Lease Agreement Identified',
        'Line Department - Send Brief for Contract Request — MOU or NDA',
        'Legal - Develop Contract and Share with Line Department',
        'Legal - Legal Engages Partner Directly or via Line Department?',
        'Legal - Line Department',
        'Line Department - Share Contract with Partner',
        'Legal - Legal Team',
        'Legal - Engage BP\'s Legal Team and Share Contract',
        'Legal - Negotiate and Reach Agreement on Terms',
        'Legal - Agreement Reached?',
        'Legal - No',
        'Legal - Yes',
        'DOA - Approve and Sign Off Internally',
        'DOA - DoA Internally Approves and Signs?',
        'DOA - No',
        'DOA - Yes',
        'DOA - Share Signed Contract with Contracting Partner',
        'BP - BP Returns Signed Contract',
        'BP - MOU / NDA / Lease Agreement Fully Signed by All Parties',
    ],

    'risk-6.1': [
        'EA - Quarterly Reporting Cycle Initiated',
        'IO - Is Site Visit Required?',
        'IO - Yes',
        'IO - Issue Site Visit Request to Client',
        'EA - Submit Information Request to Client',
        'EA - Conduct ESG Audit for Investee or Internal Stakeholder',
        'EA - Provide Advisory and Recommendations — Internal Client or Investee',
        'EA - Produce Audit Report and Site Visit Report',
        'EA - Communicate Recommendations to Client',
        'EA - Consolidate Post Monitoring Report into Quarterly ESG Report',
        'EA - Quarterly ESG Report Issued',
        'EA - No',
    ],
};



// --- PDF PAGE MAPPING ----------------------------------------------------------
// One PDF per department in the maps/ folder (e.g. maps/scm.pdf, maps/it.pdf).
// Each key maps a process ID to the page number in that department's PDF.
// Pages 1-3 in the SCM PDF are assumed to be cover/intro pages.

// --- PDF PAGE MAPPING ---------------------------------------------------------
// Pages 1-3 are cover, symbol directory, and table of contents in all PDFs.
// Process maps start on page 4. One PDF per department in the maps/ folder.
const PROCESS_PAGES = {

    // SCM — maps/scm.pdf
    'scm-1.1':   4,
    'scm-1.2.1': 5,
    'scm-1.2.2': 6,
    'scm-1.3':   7,
    'scm-1.4':   8,
    'scm-1.5.1': 9,
    'scm-1.5.2': 10,
    'scm-1.6':   11,
    'scm-1.7':   12,
    'scm-1.8':   13,
    'scm-1.9':   14,
    'scm-1.10':  15,

    // IT — maps/it.pdf
    'it-1.1':    4,
    'it-1.2':    5,
    'it-1.3':    6,
    'it-1.4':    7,
    'it-1.5':    8,
    'it-1.6':    9,
    'it-1.7':    10,
    'it-1.8':    11,
    'it-1.9':    12,
    'it-1.10':   13,
    'it-1.11':   14,
    'it-1.12':   15,
    'it-1.13.1': 16,
    'it-1.13.2': 17,
    'it-1.14':   18,
    'it-1.15':   19,
    'it-1.16':   20,
    'it-1.17':   21,

    // Finance — maps/fin.pdf
    'fin-1.1':  4,
    'fin-1.2':  5,
    'fin-1.3':  6,
    'fin-1.4':  7,
    'fin-1.5':  8,
    'fin-1.6':  9,
    'fin-1.7':  10,
    'fin-2.1':  11,
    'fin-2.2':  12,
    'fin-3.1':  13,
    'fin-4.1':  14,
    'fin-4.2':  15,
    'fin-4.3':  16,

    // HR — maps/hr.pdf
    'hr-1.1':  4,
    'hr-1.2':  5,
    'hr-1.3':  6,
    'hr-1.4':  7,
    'hr-1.5':  8,
    'hr-1.6':  9,
    'hr-1.7':  10,
    'hr-1.8':  11,
    'hr-1.9':  12,
    'hr-1.10': 13,
    'hr-1.11': 14,
    'hr-1.12': 15,
    'hr-1.13': 16,
    'hr-1.14': 17,
    'hr-1.15': 18,
    'hr-1.16': 19,
    'hr-1.17': 20,
    'hr-1.18': 21,
    'hr-1.19': 22,
    'hr-1.20': 23,
    'hr-1.21': 24,
    'hr-1.22': 25,

    // Investment — maps/inv.pdf
    'inv-1.1.1': 4,
    'inv-1.1.2': 5,
    'inv-1.1.3': 6,
    'inv-1.1.4': 7,
    'inv-1.1.5': 8,
    'inv-1.1.6': 9,
    'inv-1.2.1': 10,
    'inv-1.3.1': 11,
    'inv-1.3.2': 12,
    'inv-1.3.3': 13,
    'inv-2.1.1': 14,
    'inv-2.1.2': 15,
    'inv-2.2.1': 16,
    'inv-2.3.1': 17,

    // Risk — maps/risk.pdf
    'risk-1.1':   4,
    'risk-1.2.1': 5,
    'risk-1.2.2': 6,
    'risk-1.3':   7,
    'risk-1.4':   8,
    'risk-2.1':   9,
    'risk-2.2':   10,
    'risk-2.3':   11,
    'risk-2.4':   12,
    'risk-2.5':   13,
    'risk-2.6':   14,
    'risk-3.1':   15,
    'risk-3.2':   16,
    'risk-4.1':   17,
    'risk-5.1':   18,
    'risk-5.2':   19,
    'risk-5.3.1': 20,
    'risk-5.3.2': 21,
    'risk-6.1':   22,

    // Marketing — maps/mkt.pdf
    'mkt-1.1': 4,
    'mkt-1.2': 5,
    'mkt-1.3': 6,
    'mkt-1.4': 7,
    'mkt-1.5': 8,
    'mkt-1.6': 9,
    'mkt-1.7': 10,

    // Cosec — maps/cosec.pdf
    'cosec-1.1':   4,
    'cosec-1.2.1': 5,
    'cosec-1.2.2': 6,
    'cosec-1.3':   7,
    'cosec-1.4':   8,
    'cosec-1.5':   9,
    'cosec-2.1':   10,

    // PMO — maps/pmo.pdf
    'pmo-1.1': 4,
    'pmo-1.2': 5,
    'pmo-1.3': 6,
    'pmo-1.4': 7,
    'pmo-1.5': 8,
    'pmo-1.6': 9,
    'pmo-1.7': 10,
};
